name: UW HAI
url: http://uw-hai.github.io # Update to be CS web address

exclude: [bibble, README.md, Makefile, screenshot.png]

# Colorize code snippets with the rogue module if we want to deploy on GH.
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: grad
    name: PhD Students
  - key: ugrad-alum
    name: MS/BS Alumni
  - key: collab
    name: Collaborators
  - key: alum
    name: PhD Alumni

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  # - title: People
  #   link: /#people
  #- title: Research
    #link: /research.html
  - title: Publications
    link: /publications.html
  #- title: Code
    #link: /code.html
